version: "3"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
